### ISSUE TITLE
Document SEARCH_DOMAIN variable

### ISSUE THREAD

**Issue by scaleoutsean** [NetApp/beegfs#4]
When servers are documented w/o FQDNs, SEARCH_DOMAIN must be provided because Postfix fails to start without this in place.

https://github.com/netappeseries/beegfs/blob/135d9a04ae96f4d202300bae870c6404b77b6865/getting_started/beegfs_ha_7_2/templates/ha_cluster_group_template.j2#L24

**Comment by scaleoutsean** [comment]
Just saw it mentioned in https://github.com/netappeseries/beegfs/blob/master/roles/beegfs_ha_7_2/docs/getting_started.md#example-ha-cluster-group, closing.

**Comment by scaleoutsean** [comment]
Okay, on second thought, the link where it's documented is missing the underscore `_` - can we make that consistent with the variable name in that template above?

**Comment by iamjoemccormick** [comment]
Confirming this proposed doc change will be included in the next release.
