### ISSUE TITLE
Broken link in HA 7.2 getting started

### ISSUE THREAD

**Issue by scaleoutsean** [NetApp/beegfs#5]
> See [Override BeeGFS Configuration Defaults](https://github.com/netappeseries/beegfs/blob/master/roles/beegfs_ha_7_2/docs/docs/override_beegfs_configuration_defaults.md) for more details on how to override BeeGFS configuration on a global or per service basis.

This link is 404.

**Comment by netappeseries** [comment]
Thanks for letting us know.
